site_name: DX Test Site
theme:
  name: material
  logo: assets/dx_logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  custom_dir: theme_overrides/
plugins:
  - awesome-pages
  - search
  - mike:
      version_selector: true
copyright: Copyright &copy; HCL, 2021
extra:
  version:
    provider: mike