site_name: DX Test Site
theme:
  name: material
  logo: assets/dx_logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand
plugins:
    - awesome-pages
    - search