site_name: DX Test Site
site_url: 
theme:
  name: material
  logo: assets/dx_logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/circularlizard/test-dx-doc
repo_name: circularlizard/test-dx-doc
plugins:
  - awesome-pages
  - search
  - git-revision-date
  - mike:
      version_selector: true
copyright: Copyright &copy; HCL, 2021
extra:
  version:
    provider: mike
  alternate:
    - name: Français
      link: /fr/
      lang: fr
